language: php
os: linux
dist: xenial

env:
  global:
    - XDEBUG_MODE=coverage

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

jobs:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - sh -c "if [ '${TRAVIS_PHP_VERSION:0:2}' = '8.' ] || [ '$TRAVIS_PHP_VERSION' = 'nightly' ]; then sed -i 's/phpunit\/phpunit/sminnee\/phpunit/g' composer.json; composer config -g platform.php 7.4.11; fi"
  - sh -c "if [ '${TRAVIS_PHP_VERSION:0:2}' = '7.' ]; then sed -i 's/phpunit\/phpunit/sminnee\/phpunit/g' composer.json; fi"
  - php composer.phar install

script: php vendor/bin/phpunit --coverage-text
